name: Activity

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: lowlighter/metrics@latest
      with:
        user: manifoldfinance
        filename: profile/activity.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: header, activity, community, repositories, metadata
        plugin_activity: yes
        plugin_activity_limit: 5
        plugin_activity_days: 0
        plugin_activity_filter: issue, pr, release, fork, review, ref/create
        plugin_followup: yes
        plugin_followup_sections: repositories
        plugin_habits: yes
        plugin_habits_facts: yes
        plugin_habits_charts: no
